### ISSUE TITLE
can you make an youtube tutorial for install this midi and phyton pls?

### ISSUE THREAD

**Issue by Aidenn3** [Undawn-Programs/Undawn-Autopiano-public#3]
so i already installed python 3 on my computer and run an Win+R cmd and type "pip install mido pyautogui" and in cmd it said 'pip' is not recognized as an internal or external command,
operable program or batch file. im using translator to understand in readme.md sorry

**Comment by ReturnToFirst** [comment]
Then use command
`python -m pip install <module to install>`.
probably finding way with search about that error message would helpful.

**Comment by Aidenn3** [comment]
i got this "python -m pip install midi
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases."
